version: '3.3'
services:
  web:
    container_name: web
    ports:
      - '80:80'
    restart: always
    logging:
      options:
        max-size: 1g
    image: 'rolmos/moie-admin:${APP_VERSION}'
    deploy:
      replicas: 1
