
name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      SOURCE_DIR: "build/"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI: false
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: git config --global url."https://".insteadOf git://
      - run: yarn
      - run: yarn build

      - uses: elgohr/Publish-Docker-Github-Action@master
        name: Publish to Github Packages Registry
        with:
          name: ${{ secrets.DOCKER_REPOSITORY }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          dockerfile: Dockerfile
          tags: latest

      - uses: appleboy/ssh-action@master
        name: Deploy in cluster
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          password: ${{ secrets.AWS_PASSWORD }}
          envs: GITHUB_SHA
          scripts: |
            docker login
            docker pull ${{ secrets.DOCKER_REPOSITORY }}
            docker stop moie-admin-v2
            docker rm moie-admin-v2
            docker run --detach --name moie-admin-v2 -p 80:8080 init0203/backend-repo
