name: Moie Admin Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Build - Moie Admin
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://".insteadOf git://
    - run: npm install
    - run: CI=false npm run build
    - uses: actions/checkout@v3
    
  deployment:
      runs-on: ubuntu-latest
      needs: [build]

      steps:
        - name: Docker Login
          env:
            DOCKER_USER: ${{secrets.DOCKER_USER}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          run:
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - name: Docker Push
          env:
            REPO: rolmos/moie-admin
          run: |
            docker build -t $REPO
            docker tag $REPO:latest ${{secrets.DOCKER_USER}}/$REPO:latest
            docker push ${{secrets.DOCKER_USER}}/$REPO
          
        - name: Run the image in a container
          uses: addnab/docker-run-action@v3
          with:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/moie-admin:latest
            run: |
              echo "runing the docker image"
              echo "Testing the nodejs  app endpoints"
              echo ${{ steps.docker_build.outputs.digest }}
              
        - name: Run the image in a container
          uses: addnab/docker-run-action@v3
          with:
            host: ${{ secrets.AWS_HOST }}
            username: ec2-user
            key: ${{ secrets.AWS_PRIVATE_KEY }}
            envs: GITHUB_SHA
            scripts: |
              docker login
              cd /home/ubuntu/apps/frontend
              docker-compose pull
              docker-compose stop
              docker-compose rm moie-lucy-api
              docker-compose up -d 
        
