name: Moie Admin Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    #Building
    - uses: actions/checkout@v3
    - name: Build - Moie Admin
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://".insteadOf git://
    - run: npm install
    - run: CI=false npm run build
    - uses: actions/checkout@v3
    #Push Docker
    - uses: elgohr/Publish-Docker-Github-Action@master
      name: Publish to Github Packages Registry
      with:
        name: ${{ secrets.DOCKER_REPOSITORY }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
    #Deployment
    - uses: addnab/docker-run-action@v3
      name: Deploy in cluster
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        envs: GITHUB_SHA
        scripts: |
          docker login
          cd /home/ubuntu/apps/frontend
          docker-compose pull
          docker-compose stop
          docker-compose rm moie-lucy-api
          docker-compose up -d
